# Matrix Manipulations in Python

## Motivation
With the explosion of data, data structures that can encode multiple categories of information and for multiple entities. Structures such as vectors and matrices are commonly used. Excel sheets, for example, are matrices. We are already familiar with computational analysis that takes advantage of the tabular format such as statistical analysis.

In the more recent years, computers have become more powerful! In fact, smartphones now are magnitudes more powerful than the computers that were used to run the Apollo 11 mission!

And with more computing power comes more possibilities. Computational theories such as neural networks in the 70s are now realized and used in applications such as recommender systems (think of youtube and netflix), weather forecasting, and autonomous vehicles (think of Tesla's driverless cars).

What most people don't know is that these applications are built on top of mathematics concepts such as matrix decompositions, nonlinear transformations, matrix differentiation, and even Newton's methods!

While we will not cover how those cool models are created, we will introduce the fundamentals of translating linear algebra operations from concepts to code.

## Numpy Arrays and Matrices
In many algorithms, data is represented mathematically as a *vector* or a *matrix*. Conceptually, a vector is just a list of numbers, and a matrix is a two-dimensional list of numbers (a list of lists). This means that in theory, we can perform linear algebra operations using the structures and python methods that we already encountered (lists, arithmetic operations, loops, etc.) However, if we use those stuff, even computing basic operations like matrix multiplication are cumbersome to implement and slow to execute.

Hence, we use numpy which implemented more optimized methods for performing basic routines. After 15 years of development, the main contributors of numpy finally published a paper on this very important python package. The link to the paper published in Nature can be found [here](https://www.nature.com/articles/s41586-020-2649-2).

In [1]:
import numpy as np # As mentioned before, the "alias" np is standard for python programmers

#### Creating 1-D arrays

In [2]:
# Create a 1-D array by wrapping a list with NumPy's array() function.
a = np.array([1, 4, 3])
a

array([1, 4, 3])

In [3]:
print(a)

[1 4 3]


Notice that the displayed values in the print statement do not contain commas.

#### Creating 2-D arrays

In [4]:
# Create a 2-D array by wrapping a list of lists with NumPy's array() function.
A = np.array([[1, 4, 3],
              [2, 0, 3]])
A

array([[1, 4, 3],
       [2, 0, 3]])

In [5]:
print(A)

[[1 4 3]
 [2 0 3]]


## Basic Operations on Arrays

### Adding, Subtracting, Multiplying, and Dividing a Scalar To An Array

In [6]:
print(a)
print(a + 5)

[1 4 3]
[6 9 8]


In [7]:
# this is also commutative
print(5 + a)

[6 9 8]


In [8]:
# same thing for multiplication
print(a * 5)

[ 5 20 15]


In [9]:
# 
a - 5

array([-4, -1, -2])

In [10]:
a / 5

array([0.2, 0.8, 0.6])

<div class="alert alert-info">
    Note: All arithmetic operations between an array and a scalar applies the operation element-wise on the array.
</div>

### Operations on Arrays with Same Dimensions

In [11]:
a

array([1, 4, 3])

In [12]:
b = np.array([2, 0, 3])

print(a)
print(b)

[1 4 3]
[2 0 3]


In [13]:
a + b

array([3, 4, 6])

In [14]:
a - b

array([-1,  4,  0])

In [15]:
a * b

array([2, 0, 9])

In [16]:
a / b

/Users/johntitusjungao/opt/anaconda3/envs/py4mathmods/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([0.5, inf, 1. ])

<div class="alert alert-danger">
    Note: Dividing by zero will give you a warning like the one above. Also, the output shows <b>inf</b> which is the data type used to represent the results when dividing by 0.
</div>

In [17]:
a ** b

array([ 1,  1, 27])

In [18]:
a % b

/Users/johntitusjungao/opt/anaconda3/envs/py4mathmods/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([1, 0, 0])

In [19]:
# Let's set a 2-D array to perform operations
B = np.array([[3, 1, 7],
              [1, 5, 4]])

print('Matrix A:')
print(A)
print()
print('Matrix B:')
print(B)

Matrix A:
[[1 4 3]
 [2 0 3]]

Matrix B:
[[3 1 7]
 [1 5 4]]


In [20]:
A + B

array([[ 4,  5, 10],
       [ 3,  5,  7]])

In [21]:
A - B

array([[-2,  3, -4],
       [ 1, -5, -1]])

In [22]:
A * B

array([[ 3,  4, 21],
       [ 2,  0, 12]])

In [23]:
A / B

array([[0.33333333, 4.        , 0.42857143],
       [2.        , 0.        , 0.75      ]])

In [24]:
A ** B

array([[   1,    4, 2187],
       [   2,    0,   81]])

In [25]:
A % B

array([[1, 0, 3],
       [0, 0, 3]])

Note that both a and A are both `numpy ndarray` types. Think of it as n-dimensional arrays with different values for n.

In [26]:
type(a)

numpy.ndarray

In [27]:
type(A)

numpy.ndarray

### Multiplying Arrays

Matrix multiplication is done using the `.dot()` method

In [28]:
A.dot(a)

array([26, 11])

### Getting The Transpose
for transpose, use the attribute `.T`

In [29]:
A.T

array([[1, 2],
       [4, 0],
       [3, 3]])

### Array Attributes

```Python
dtype  - # The type of the elements in the array
ndim   - # The number of axes (dimensions) of the array
shape  - # A tuple of integers indicating the size of each dimension
size   - # The total numer of elements in the array
```

In [30]:
a.dtype

dtype('int64')

In [31]:
A.dtype

dtype('int64')

In [32]:
a.ndim

1

In [33]:
A.ndim

2

In [34]:
a.shape

(3,)

In [35]:
A.shape

(2, 3)

In [36]:
a.size

3

In [37]:
A.size

6

### Array Creation Routines
Aside from casting other structures such as list as arrays using np.array(), Numpy also have ways to generate commonly used structures.

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
ones = np.ones((4, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
zeros = np.zeros((4, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<div class="alert alert-danger">
    Note: Elements in a numpy array must have a uniform data type (all ints, all floats, etc.).
</div>

In [42]:
# to change data types, you can use the astype() method

In [43]:
I.dtype

dtype('float64')

In [44]:
I.astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

You can also get the **diagonal**, **lower-triangular portion**, and **upper-triangular portion** of a matrix.

In [45]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.triu(ones)

array([[1., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [47]:
np.tril(ones)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [48]:
np.diag(ones)

array([1., 1., 1., 1.])

<div class="alert alert-success">
    Create the following matrices below without using np.array()
</div>

In [49]:
np.array([[1, 1, 1], [0, 1, 1], [0, 0, 1]])

array([[1, 1, 1],
       [0, 1, 1],
       [0, 0, 1]])

In [50]:
np.array([[-2, 3, 3], [-2, -2, 3], [-2, -2, -2]])

array([[-2,  3,  3],
       [-2, -2,  3],
       [-2, -2, -2]])

### Slicing and Indexing Arrays

#### Indexing 1-D arrays
Indexing 1-D arrays is the same syntax as in lists. That is, it follows the following format:

`x[start:stop:step]`

In [51]:
# example
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# access an element by indexing
x[3]

3

In [53]:
# access the first 4 elements
x[0:4]

array([0, 1, 2, 3])

In [54]:
# alternative
x[:4]

array([0, 1, 2, 3])

In [55]:
# getting elements from 3 to 9
x[3:8]

array([3, 4, 5, 6, 7])

#### Indexing 2-D arrays

Correspondingly, for 2D arrays the following are the syntax:

In [56]:
# create a sample 2D array
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
# access the first row
A[0]

array([1, 2, 3, 4])

In [58]:
# access the second row
A[1]

array([5, 6, 7, 8])

In [60]:
# there is no third row
A[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

When we try to get an index which is beyond the dimensions of our array, we get the error above.

In [ ]:
# accessing column 0
A[:, 0]

In [ ]:
# accessing column 1
A[:, 1]

In [ ]:
# accessing element in row 1, column 2
A[1, 2]

In [ ]:
# accessing all rows from column 2 onwards
A[:, 2:]

### Shaping Arrays

You can reshape numpy arrays using the `reshape()` array method.

In [ ]:
A

In [ ]:
A.shape

In [ ]:
# reshape into 1 x 8
A.reshape((1, 8))

In [ ]:
# reshape into 1 x 8
A.reshape((8, 1))

In [ ]:
A.reshape((4, 2))

### Flatten
You can convert a 2-D array into a 1-D array using the `ravel()` method

In [ ]:
A.ravel()

In [ ]:
A.reshape(8)

## Numerical Computing With Numpy

### Universal Functions
A *universal function* is one that operates in the entire array in an element-wise manner.

np.exp() / np.log - # element-wise exponentiation and natural log
np.minimum() / np.maximum() - # element-wise minimum and maximum of two arrays
np.sqrt() - # positive square root element-wise
np.sin(), np.cos(), np.tan(), etc. - # element-wise trigonometric operations

In [ ]:
# calculate the absolute value element-wise
np.abs(A)

In [ ]:
# calculate element-wise exponential
np.exp(A)

In [ ]:
np.log(A)

In [ ]:
np.minimum(np.ones((3, 3)), np.eye(3))

In [ ]:
np.maximum(np.ones((3, 3)), np.eye(3))

In [ ]:
np.sqrt(A)

In [ ]:
# trigonometric functions
np.sin(A)

<div class="alert alert-info">
    Tip: Always use universal numpy functions when working with arrays rather than using the math package.
</div>

### Other Useful Array Methods

In [ ]:
A

In [ ]:
np.all(A > 0)

In [ ]:
np.any(A <= 0)

In [ ]:
A.max()

In [ ]:
A.max(axis=1)

In [ ]:
A.max(axis=0)

In [61]:
A.min()

1

In [62]:
A.min(axis=1)

array([1, 5])

In [63]:
A.min(axis=0)

array([1, 2, 3, 4])

In [64]:
A.mean()

4.5

In [65]:
A.mean(axis=1)

array([2.5, 6.5])

In [66]:
A.mean(axis=0)

array([3., 4., 5., 6.])

In [67]:
A.std()

2.29128784747792

In [68]:
A.std(axis=1)

array([1.11803399, 1.11803399])

In [69]:
A.std(axis=0)

array([2., 2., 2., 2.])

### Generating Random Numbers

In [70]:
# generate random number from standard normal distribution
M_random = np.random.randn(3, 4)
M_random

array([[ 1.93519019,  0.45877226,  1.06374236, -0.02770264],
       [ 0.07856257,  1.51447694,  0.81833443,  0.04327172],
       [-0.88400054, -0.2032397 , -1.57503247,  1.00329942]])